# node1.toml
[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://192.168.1.134:4723"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\", \"appium:platformVersion\": \"13\", \"appium:deviceName\": \"Lenovo\", \"appium:automationName\": \"UiAutomator2\"}"
]